name: jira_api_server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  jira_api:
    git:
      url: https://github.com/mishkov/jira_api.git
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3

